const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)};
function bindRange(id,out,format=v=>v){const el=$(id),o=$(out);const update=()=>{el.style.setProperty('--val',`${el.value}%`);o.textContent=format(el.value);$('#savedState').innerHTML='<i></i>正在同步…';clearTimeout(el.timer);el.timer=setTimeout(()=>$('#savedState').innerHTML='<i></i>参数已同步',450)};el.addEventListener('input',update);update();return el}
const noise=bindRange('#noiseRange','#noiseValue');const reverb=bindRange('#reverbRange','#reverbValue',v=>`${v}%`);
const micSwitch=$('#micSwitch');micSwitch.onchange=()=>{const on=micSwitch.checked;$('#micMaster').classList.toggle('off',!on);$('#audioControls').classList.toggle('disabled',!on);$('#audioControls').setAttribute('aria-disabled',String(!on));$('#micStatus').textContent=on?'麦克风已开启，声音处理功能正常工作':'麦克风已静音，所有声音处理已暂停';if(!on&&mediaRecorder?.state==='recording')mediaRecorder.stop();toast(on?'麦克风已开启':'麦克风已静音')};
$$('.preset-row button').forEach(b=>b.onclick=()=>{$$('.preset-row button').forEach(x=>x.classList.remove('active'));b.classList.add('active');reverb.value=b.dataset.value;reverb.dispatchEvent(new Event('input'))});
$$('.switch input').forEach(s=>s.onchange=()=>toast(`${s.closest('article')?.querySelector('h3')?.textContent||'灯效'}已${s.checked?'开启':'关闭'}`));
const root=document.documentElement;$$('#colorPicker button').forEach(b=>b.onclick=()=>{$$('#colorPicker button').forEach(x=>x.classList.remove('active'));b.classList.add('active');root.style.setProperty('--light-color',b.dataset.color);toast('灯光颜色已更新')});
$('#customColor').oninput=e=>{root.style.setProperty('--light-color',e.target.value);$$('#colorPicker button').forEach(x=>x.classList.remove('active'))};$('#lightMode').onchange=e=>toast(`已切换为${e.target.value}`);
const canvas=$('#waveform'),ctx=canvas.getContext('2d');function idleWave(t=0){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.beginPath();for(let x=0;x<canvas.width;x+=3){const a=Math.sin(x*.11+t)*4+Math.sin(x*.035+t*.6)*7;ctx.moveTo(x,26-a);ctx.lineTo(x,26+a)}ctx.strokeStyle='#6f7180';ctx.lineWidth=1;ctx.stroke()};idleWave();
let mediaRecorder,chunks=[],stream,timer,audioUrl,startAt,anim;const rec=$('#recorder'),recordBtn=$('#recordBtn'),play=$('#playBtn'),time=$('#recordTime'),label=$('#recordLabel');
recordBtn.onclick=async()=>{if(mediaRecorder?.state==='recording'){mediaRecorder.stop();return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);chunks=[];mediaRecorder.ondataavailable=e=>chunks.push(e.data);mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());clearInterval(timer);cancelAnimationFrame(anim);audioUrl=URL.createObjectURL(new Blob(chunks,{type:mediaRecorder.mimeType}));play.disabled=false;rec.classList.remove('recording');label.textContent='录音完成';time.textContent='点击播放试听';idleWave();toast('录音已准备好');};mediaRecorder.start();rec.classList.add('recording');label.textContent='正在录音';startAt=Date.now();timer=setInterval(()=>{const s=Math.floor((Date.now()-startAt)/1000);time.textContent=`00:${String(s).padStart(2,'0')} / 00:30`;if(s>=30)mediaRecorder.stop()},250);animateWave()}catch(e){toast('请允许浏览器使用麦克风后重试')}};
function animateWave(){const t=Date.now()/180;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.beginPath();for(let x=0;x<canvas.width;x+=3){const a=(Math.sin(x*.08+t)*.5+.5)*18+3;ctx.moveTo(x,26-a);ctx.lineTo(x,26+a)}ctx.strokeStyle='#8b7cff';ctx.stroke();anim=requestAnimationFrame(animateWave)}play.onclick=()=>{if(audioUrl){new Audio(audioUrl).play();toast('正在播放录音')}};$('.device-pill button').onclick=()=>toast('设备连接正常');$('.icon-btn').onclick=()=>toast('拖动参数即可实时调节声音');
